### ISSUE TITLE
The same data appears twice

### ISSUE THREAD

**Issue by tangbao0002** [microsoft/sql-server-samples#1003]
In SqlServer 2014 version, The table is cteated with the following sql:
     **CREATE TABLE [dbo].[Region](
	[Id] [varchar](19) NOT NULL,
	[RegionName] [nvarchar](100) NULL,
	[Pinyin] [nvarchar](100) NULL,
	[Sequence] [int] NULL,
	[RegionType] [tinyint] NOT NULL,
	[RegionState] [tinyint] NOT NULL,
	[ParentRegionId] [varchar](19) NULL,
	[CreateTime] [datetime] NULL,
	[CreateUserId] [varchar](19) NULL,
	[UpdateTime] [datetime] NULL,
	[IsAlive] [bit] NOT NULL,
	[Longitude] [decimal](10, 7) NULL,
	[Latitude] [decimal](10, 7) NULL,
	[CheckDay] [int] NULL,
	[EnableTime] [datetime] NULL,
	[RegionNumber] [int] NULL,
	[AreaID] [int] NULL,
	[SourceType] [smallint] NULL,
	[RegionCode] [varchar](20) NULL,
	[RootRegionId] [varchar](19) NULL,
 CONSTRAINT [PK__Region__ACD844A332E67BF3] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]**

**insert into Region(Id, RegionName,RegionType, RegionState, ParentRegionId) values ('1', 'Test1', 1, 1, null);
insert into Region(Id, RegionName,RegionType, RegionState, ParentRegionId) values ('2', 'Test2', 2, 1, '');**

And when I try to query data with the SQL as the following: 
     **select  * 
      from Region a
inner join Region b
        on a.Id = b.Id 
     where a.IsAlive =1 and( a.ParentRegionId IS NULL  OR a.ParentRegionId = N'')**
![image](https://user-images.githubusercontent.com/12482184/159637008-3924e568-902f-4e8b-b6eb-941e0f9aff84.png)
**The same data appears twice!**

**Comment by Augeraki** [comment]
hello, 
if you prefer an entry to not appear twice when quering your database maybe a solution would be to use the 
select distinct * . This will not return identical lines more than one time. 
I hope this helps . This was my first response.
