### ISSUE TITLE
Expose assessment thresholds in portal

### ISSUE THREAD

**Issue by treytro** [microsoft/sql-server-samples#1036]
This is in reference to the SQL best practices assessment on Azure IaaS VM.

For checks such as, DbSpaceAvailable ("Average available space in data files is less than threshold"), the threshold appears to be internal to the assessment.  

It would be great if we could set our own custom thresholds in the Azure portal.

**Comment by ebruersan** [comment]
Thank you for your feedback. We do now show the values in the message. 
Customization is something we would love to provide but we won't be able to in the short term unfortunately.
