### ISSUE TITLE
not able to pull  microsoft/mssql-server-2014-express-windows

### ISSUE THREAD

**Issue by plakhlani** [Microsoft/sql-server-samples#104]
When I try to pull sql 2014 express on windows 10 with docker, I get an error. See following for the example:
`PS C:\Users\Prashant> docker pull microsoft/mssql-server-2014-express-windows
Using default tag: latest
latest: Pulling from microsoft/mssql-server-2014-express-windows
1239394e5a8a: Downloading
1277c1a047c0: Download complete
7836e8cf3dc2: Download complete
bfff1a38c8ba: Download complete
f82efbd6f52b: Download complete
5a3874353855: Download complete
3487f0e37f4b: Download complete
19dee413779d: Download complete
6e9dc0f189d0: Download complete
aaa4f05bd7e7: Download complete
124c608fd8c6: Download complete
fa9da3d0ab45: Download complete
unknown blob`

**Comment by perrysk-msft** [comment]
Thanks for trying out the sql 2014 express docker image. The image requires Windows Server Core TP5 v10.0.14300.1030 and is currently not compatible with Windows 10.
