### ISSUE TITLE
How to Calculate business hours or working hours in SQL Query

### ISSUE THREAD

**Issue by Algawzy** [microsoft/sql-server-samples#1107]
Hi folks,
How could calculating working hours between two date which is the working hours are from 8:00 am to 11:00 pm
![2-15-2023 12-26-00 AM](https://user-images.githubusercontent.com/115530963/218866851-cb1771e9-23e3-4202-9f7e-be11d1542d45.png)

**Comment by bishnabob** [comment]
Probably best asking this on StackOverflow.
