### ISSUE TITLE
High DPI screen issue - Blue Yonder Ticket Reservation System

### ISSUE THREAD

**Issue by iizotov** [Microsoft/sql-server-samples#144]
Scaling issue on high-dpi screens on both Blue Yonder Ticket Reservation System forms. A quick fix that worked for me was to set autoscalemode  to DPI on the form level.

Screenshot taken on Windows Server 2016 TP5 over an RDP connection

![scaling issue](https://cloud.githubusercontent.com/assets/7712335/19567025/2c6e5d88-96a1-11e6-9fb3-94930db8d9ab.png)

**Comment by jodebrui** [comment]
Thanks very much for reporting the issue and offering the solution!
I made the updates to the source code. Could you validate on your end, as I don't have a high DPI screen?

**Comment by iizotov** [comment]
Hi,

The issue is fixed, cheers
