### ISSUE TITLE
Unknown Customers in DW due to NULL BuyingGroupID in WideWorldImporters.Sales.Customers

### ISSUE THREAD

**Issue by boscorat** [Microsoft/sql-server-samples#154]
I've generated data in the WideWorldImporters database and run the SSIS package to populate the DW database.  When I do this I get a large number of transactions with Unknown customers.
The reason appears to be that there are only two buying groups defined in the source database (Tailspin Toys and Wingtip Toys) and the rest of the customers have NULL for their BuyingGroupID.  It looks as though this is acceptable, as not all customers would be part of a buying group, but the [Integration].[GetCustomerUpdates] procedure INNER JOIN's on to the BuyingGroups table.  Due to this INNER JOIN, I'm only getting customer records in the DW database for Tailspin & Wingtip customers.
I've tried changing the INNER JOIN's in the [Integration].[GetCustomerUpdates] procedure, but this then breaks integrity constaints in the DW database so the customers won't load.
It may be that all customers should have a default BuyingGroup and something has gone wrong during my initial population of data, but I've checked through the scripts and it doesn't look like it.
Can anyone help?

**Comment by jodebrui** [comment]
Thanks. This is a bug in the Integration procedure. We’ll get this fixed.

**Comment by jodebrui** [comment]
Apologies for the delayed response. The issue was fixed, but I neglected to close the issue.
The fix is checked in, and will be included in the next release of the sample DB.
