### ISSUE TITLE
Invalid volume spec when using -v parameter

### ISSUE THREAD

**Issue by markallisongit** [Microsoft/sql-server-samples#156]
I'm running this on Hyper-V 2016:

`docker run -d -p 1433:1433 -v C:/temp/:C:/temp/ -e sa_password=<MY_SUPERSECURE_PASSWORD> -e ACCEPT_EULA=Y microsoft/mssql-server-windows-express`

Gives me this error
```
docker : C:\Program Files\Docker\docker.exe: Error response from daemon: invalid bind mount spec "C:/temp/:C:/temp/": invalid volume specification:
'C:/temp/:C:/temp/': invalid mount config for type "bind": GetFileAttributesEx c:\temp\: The filename, directory name, or volume label syntax is
incorrect..
    + CategoryInfo          : NotSpecified: (C:\Program File... is incorrect..:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by perrysk-msft** [comment]
Hi markallisongit - 

Thanks for trying out the SQL Docker image and reporting this issue!

Could you please post this issue along with docker info & docker version output at: https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers

We'll probably need to have some back & forth discussion to get the right details and that’s really hard to do in a comment feed.

Thanks, Perry
