### ISSUE TITLE
Sql server localdb 2016 is not supported

### ISSUE THREAD

**Issue by Kasper888** [Microsoft/sql-server-samples#163]
I tried to restore the .bak under (LocalDB)\MSSQLLocalDB instance but failed as it doesn't support FileStream feature, is there any way to exclude the filestream and only restore the .mdf and .ldf ?

**Comment by jodebrui** [comment]
The full version of the sample DB is not supported on LocalDB. To use the full version use Express, Developer, or any other edition.
The limited “standard” version should work on localdb SP1:
https://github.com/Microsoft/sql-server-samples/releases/download/wide-world-importers-v1.0/WideWorldImporters-Standard.bak

Thanks,
Jos
