### ISSUE TITLE
Cannot restore WideWorldImporters-Full to Express version DB Engine.

### ISSUE THREAD

**Issue by ghost** [Microsoft/sql-server-samples#169]
I am using:
Windows 10 Pro 64bit
SQL Server 2016 Express SP1 with CU3

Restore both WideWorldImporters-Full and WideWorldImportersDW-Full, It show (SQL server service not starting with error code: 3414)

I stay back and try the legacy version:
WideWorldImporters-Standard.bak
and
WideWorldImportersDW-Standard.bak

It success without any error.

**Comment by jodebrui** [comment]
Sounds like you may not have enough available memory. How much memory is available to SQL Server when you perform the restore?

**Comment by jodebrui** [comment]
Was not able to repro. If you run into this issue again, please share the SQL Server errorlog.
