### ISSUE TITLE
sql vnext url doesn't work

### ISSUE THREAD

**Issue by gigatexal** [Microsoft/sql-server-samples#175]
`ENV sql_vnext_download_url "https://go.microsoft.com/fwlink/?linkid=829176"` <-- is broken

error:

 ---> Running in e82b95de732a
Exception calling "DownloadFile" with "2" argument(s): "The remote server
returned an error: (404) Not Found."
At line:1 char:1
+ (New-Object System.Net.WebClient).DownloadFile('https://go.microsoft. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by perrysk-msft** [comment]
[@gigatexal]
Thanks - We are aware of the issue and we are working on it. We'll update the URL shortly.

**Comment by gigatexal** [comment]
Awesome! I know this is probably bad form but since I have your attention is there any chance to get the 'Replication' feature supported? Currently it does just the engine

**Comment by gigatexal** [comment]
Actually disregard I'll make a new issue. Apologies.

**Comment by gigatexal** [comment]
That new URL works. Much appreciated.

**Comment by perrysk-msft** [comment]
[@gigatexal] 
We are currectly exploring how AlwaysOn could work with Containers but we do not have any timelines that we can share at this point. Could you please share a bit more on your scenario? Are you primarily interested in suporting Availability/Disaster Recovery scenarios?

**Comment by perrysk-msft** [comment]
[@gigatexal]
No problem - Thank you gigatexal!

**Comment by gigatexal** [comment]
We use replication heavily here. I'd like to be able to spin up instances and have the databases be attached and be able to use one as a publisher in transactional replication not merely support subscription only. Another feature that would be crucial is the ability to run Sql server jobs. The holy Gail of all of this would be to just have /Features=SQL and have it all just work. But I suspect there's more of the underlying windows core image that I don't know about. 

We don't use high availability or always on as of yet. But we do use SSIS packages and full text indexes.

**Comment by gigatexal** [comment]
Would you prefer a new issue tracker entry or keep this thread?

**Comment by perrysk-msft** [comment]
[@gigatexal]
Yes please. We are moving to: https://github.com/Microsoft/mssql-docker so I would really appreciate if you could open an issue there so we can track it separately.

Thanks!

**Comment by gigatexal** [comment]
Will do.
