### ISSUE TITLE
Doesn't deploy to Azure

### ISSUE THREAD

**Issue by EndUser2017** [Microsoft/sql-server-samples#183]
The ones that say they work for Standalone SQL and AzureDB or Azure DW is inaccurate for Azure. You cannot deploy DW as a data warehouse component just a regular sql azure database. The History Tables and other pieces for Temporal requirements do not work either as the versioning does not exist which then breaks the helpful data generation sproc. Can this please get corrected as it is sort of hard to demo features in Azure if the sample which is supposed to be the newest to replace adventureworks does not work out of the box... if one thing is broken who knows what else is, that is not encouraging at all to new Dev's who expect to start with a working component

**Comment by jodebrui** [comment]
Which sample(s) are broken specifically?

**Comment by EndUser2017** [comment]
DataLoadSimulation sproc does not work ... this is from the lack of the system versioning being off and history tables not being present from what I can tell some parts need

**Comment by EndUser2017** [comment]
From what I can tell the DataLoadSimulation sproc DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad, Line 25 [Batch Start Line 0]
SYSTEM_VERSIONING is not turned ON for table Applicaiton.Cities ... I feel safe saying pretty much any table that has an associated Archive table should have its partner containing a temporal table if I am following this I will see if I can get a full list of the affected tables... standby

**Comment by jodebrui** [comment]
I assume you are referring to the WideWorldImporters sample database?

Could you include the repro steps?
How did you deploy the database? Did you download the .bacpac?

**Comment by EndUser2017** [comment]
Place to focus 

...I downloaded bacpac from the the linked file for a premier Azure tier...
....I deployed via the bacpac file in azure storage...
...after those were created I executed the DataLoadSimulation sproc which broke down in the middle of the initial run ... 

hold on I am doing a rebuild from scratch so I can get the first message I got ...

**Comment by EndUser2017** [comment]
...Note during the Import of the DB from the backpac... the tables are flagged as temporal tables 'hourglass' icon  then it disappears after the import is completed...

I initiated the dataload script below with this syntax

EXECUTE DataLoadSimulation.PopulateDataToCurrentDate
        @AverageNumberOfCustomerOrdersPerDay = 60,
        @SaturdayPercentageOfNormalWorkDay = 50,
        @SundayPercentageOfNormalWorkDay = 0,
        @IsSilentMode = 1,
        @AreDatesPrinted = 1;

I get this error after about 30 sec of runtime...

Successfully removed row level security
Successfully applied row level security
Successfully removed row level security
Wed Jun 01, 2016
 
Msg 41359, Level 16, State 0, Procedure DataLoadSimulation.RecordColdRoomTemperatures, Line 33 [Batch Start Line 0]
A query that accesses memory optimized tables using the READ COMMITTED isolation level, cannot access disk based tables when the database option READ_COMMITTED_SNAPSHOT is set to ON. Provide a supported isolation level for the memory optimized table using a table hint, such as WITH (SNAPSHOT).

I know OLTP tables require some playing with the hints mentioned above but I this is the first break...

**Comment by jodebrui** [comment]
The following database option needs to be configured:
ALTER DATABASE CURRENT SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT=ON

I’ll follow up to make sure this is configured correctly in the bacpac.

**Comment by EndUser2017** [comment]
Awesome... Sproc is building the sample data now...  now how about the Datawarehouse variant... is our only choice to load the sample as a standard Sql Azure DB... I have had no luck doing it as a Data warehouse since the bacpac does not restore the same way a stand db does ... least I cannot  simply click import Database in Azure and select the file to have it created as a data warehouse ... doing so from Sql ssms even selecting datawarehouse from it results in a  unknown edition error ...  Am I missing something here as well?

**Comment by jodebrui** [comment]
Are you trying to load the bacpac in Azure SQL DW? That will not work. The sample DB only supports SQL Server and Azure SQL DB.

For an Azure SQL DW sample, you can take a look at this one:
https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/contoso-data-warehouse

**Comment by EndUser2017** [comment]
...Well that would do it... Thank you...
