### ISSUE TITLE
Provide MDF sample database files

### ISSUE THREAD

**Issue by julielerman** [Microsoft/sql-server-samples#245]
The array of options on http://msftdbprodsamples.codeplex.com/ is a great resource.

But with CodePlex going away, it would be helpful to have additional database files in this repository, which I believe will be the official place when codeplex is gone. 

That way people who are using lighterweight tools like sqlcmd and don't have access to SSMS or sqlpackage.exe can still get sample databases to work with.

Thanks

**Comment by jodebrui** [comment]
Hi,


Have you seen the download page for the WideWorldImporters sample DB?

https://github.com/Microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0


Is this what you were looking for?



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by julielerman** [comment]
hi sorry I missed this notification. Thanks but no I was hoping for the mdf version of adventureworksLT. I know it's "retired" but you DO provide it as a bacpac here and its the only sample db for Azure SQL, so it must be relevant. Therefore an mdf version of it would be nice to have as well. Not a big deal but just thought I'd try. :)

**Comment by jodebrui** [comment]
The WideWorldImporters DBs work with Azure SQL DB, and their download page has bacpacs for the same.
I only just now noticed that there is the adventureworkslt.bacpac in the repo (not release page). I don’t know what it’s doing here, as this is not source code, and there is no readme. I will follow up on the same.

Thanks,
Jos
