### ISSUE TITLE
Typo in release readme.md.

### ISSUE THREAD

**Issue by way0utwest** [Microsoft/sql-server-samples#248]
I can't find the release md file for the WWI sample. The descriptions for the .bacpac for OLTP and DW versions is the same. One should saw data warehousing, and one should be for OLTP. If you have a location in the repo for these files, I can fork and provide a PR.

**Comment by jodebrui** [comment]
Which page are you looking at?

I’m looking at: https://github.com/Microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0
I do see the differences in description of the OLTP and OLAP databases.


Thanks,
Jos

**Comment by way0utwest** [comment]
Jos,

My apologies. I could have sworn this was OLTP and OLTP for both versions of the sample. Please close the issue, or I can delete it .

Steve
