### ISSUE TITLE
RxSqlServerData Missing Import

### ISSUE THREAD

**Issue by cwburggrabe** [Microsoft/sql-server-samples#262]
I'm am quite new to using Python and SQL Machine Learning and while working through the tutorial here: "https://microsoft.github.io/sql-ml-tutorials/python/rentalprediction/step/2.html" I got stuck on Step 2.2 where we run the external python script to fetch the data.

Using PyCharm, I get a red error underline for the RxSqlServerData import.

`from revoscalepy.computecontext.RxInSqlServer import RxSqlServerData`

Attempting to run the script produces `ImportError: cannot import name 'RxSqlServerData'`

I was successfully able to run the example you have here in SQL Management studio and get the predictions but, I would like to try the external script.

Is there something I might be missing, or perhaps I overlooked a step in being able to do this.

**Comment by uc-msft** [comment]
It should be just:

`from revoscalepy import RxSqlServerData`

**Comment by HumaSatti** [comment]
I have same issue and same run on sql but failed to run on Python or even in VSCode it also fail to run and gave the same error on revoscalepy

**Comment by arijitsharmila** [comment]
Did you get the solution? I've same problem, my python services shows revoscalepy but it doesn't work
