### ISSUE TITLE
Issue with Python 3.6.3 and pip install virtualenv

### ISSUE THREAD

**Issue by PhillipStL** [Microsoft/sql-server-samples#294]
When I follow the steps to "Create Python apps using SQL Server on Windows"
pip install virtualenv #To create virtual environments to isolate package installations between projects
I get the following error

C:\>pip install virtualenv
Collecting virtualenv
  **Could not fetch URL https://pypi.python.org/simple/virtualenv/: There was a problem confirming the ssl certificate: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:777) - skipping
  Could not find a version that satisfies the requirement virtualenv (from versions: )
No matching distribution found for virtualenv**

The pip version is 9.0.1

**Comment by absin1** [comment]
`pip install --upgrade virtualenv`

Refer [this](https://github.com/pypa/pip/issues/4436) issue
