### ISSUE TITLE
Issue with Python 3.6.3 and pip install pyodbc

### ISSUE THREAD

**Issue by PhillipStL** [Microsoft/sql-server-samples#295]
When I follow the steps to "Create Python apps using SQL Server on Windows"
pip install pyodbc

**_Collecting pyodbc
  Could not find a version that satisfies the requirement pyodbc (from versions: )
No matching distribution found for pyodbc_**

**Comment by uc-msft** [comment]
Try below:

`pip install --upgrade pyodbc`

**Comment by juanjovip24** [comment]
THANKS YOU uc-msft

**Comment by C0rVette** [comment]
This did not work for me. I am unable to load this install. Any other suggestions?
