### ISSUE TITLE
Compatibility with SQL 2012 and VS 2013

### ISSUE THREAD

**Issue by rushabh138** [Microsoft/sql-server-samples#296]
Is WideWorldImportersDW is compatible with SQL 2012 and VS 2013? Is it backward compatible?

I want to use WideWorldImportersDW for SSAS - Learning. However, I've licensed version of SQL 2012 and I want to continue using licensed version only. If WideWorldImportersDW is not compatible with SQL 2012 then can you please suggest which sample database should I use for SQL 2012 and SSAS - Learning?

Appreciate your help!

**Comment by jodebrui** [comment]
WideWorldImporters works with SQL Server 2016 and later. You can download the latest version of SQL Server Developer or Express Edition for free here: https://www.microsoft.com/en-us/sql-server/sql-server-downloads


For legacy versions of SQL Server there is the legacy sample of AdventureWorks: https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks2012



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rushabh138** [comment]
Thanks for detail response. Appreciate your suggestion.
