### ISSUE TITLE
Issue with IOT Car in winforms

### ISSUE THREAD

**Issue by skdevelopers** [Microsoft/sql-server-samples#318]
There is variable naming issue on path 
https://github.com/Microsoft/sql-server-samples/blob/master/samples/applications/iot-connected-car/WinFormsClient/sample-sql-queries.sql
			MIN(TransmissionGearPosition) AS MinGearPosition,
			MAX(TransmissionGearPosition) AS MinGearPosition,
on line 37 same name for Max Method used as Allies of Max Gear Position.
Mian Salman.

**Comment by perrysk-msft** [comment]
Thanks @skdevelopers! The column alias has now been updated and this issue is closed.
