### ISSUE TITLE
Update .gitignore file?

### ISSUE THREAD

**Issue by paschott** [Microsoft/sql-server-samples#321]
Would it make sense to update the .gitignore file to exclude common VS artifacts based on patterns instead of using explicit filenames?  There's an example file here: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore.

The only change I've ever had to make to this is to not exclude "publish.xml" files because SSDT uses that extension if someone saves a publish profile into a project, but that doesn't necessarily apply here.

**Comment by jodebrui** [comment]
Yes, that would make sense.
If you have a chance, could you submit a pull request with that change?

**Comment by paschott** [comment]
I was trying to submit a pull request with the change, but kept getting a "no differences found". I'll try again.

**Comment by jodebrui** [comment]
I see that you managed to submit the pull request. Thanks very much for your contribution!

Jos
