### ISSUE TITLE
Demo user password not working

### ISSUE THREAD

**Issue by ghotz** [microsoft/sql-server-samples#334]
Not sure what happened, I remember that it worked in the past but the passwords for alice@contoso.com and rachel@contoso.com in the Clinic security demo don't work (ASP Identity in clinic.bacpac)

**Comment by DRediske** [comment]
Can you confirm that you have checked the following: 
Your website is not having connectivity issues with your database.
You are using the correct password, per the directions (on the readme for the root of the clinic demo).

**Comment by ghotz** [comment]
No connectivity issues (as a workaround for the RLS demo I created two new users via the web site and updated the ApplicationUserPatients table with the new IDs and everything works), as a password I'm using "Password1!"

**Comment by ghotz** [comment]
Hi again, I forgot several times to follow up on this, sorry about that, but I found out in Configuration.cs that the password is **Password!1** and not **Password1!** as stated in the readme.md in https://github.com/Microsoft/sql-server-samples/tree/master/samples/features/security/contoso-clinic directory. So it was just the two last chars flipped :-)
