### ISSUE TITLE
$result variable is not set, throwing an exception in the following check

### ISSUE THREAD

**Issue by oaksboard** [Microsoft/sql-server-samples#336]
hello!

the current runbook script is missing assignation of $result variable, resulting in "Failed ScriptHalted" error.
line 208 should start with "$result = Post-OMSData...", instead $result is not set.

https://github.com/Microsoft/sql-server-samples/blob/7e3ce6c4917fb7fef23dbebc7e39111196ee0fbe/samples/features/sql-data-sync/DataSyncLogPowerShellRunbook.ps1#L208

if there is only one sync group, the data is written to OMS anyway, but if there is more than one the script stops after the first one.

bye,
oskar

**Comment by douglaslMS** [comment]
@oaksboard Oskar, Thank you for bring this to our attention. I have fixed the script. Please let us know if you notice anything else.
