### ISSUE TITLE
Error: 17113, Severity: 16, State: 1

### ISSUE THREAD

**Issue by Deepankar01** [Microsoft/sql-server-samples#344]
This is still happening in **mac** any solution will help 

https://github.com/Microsoft/sql-server-samples/issues/160 this was `closed` but still not resolved why it was closed as `clueless`  

`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Passw0rd@123' -e 'MSSQL_PID=Enterprise' -p 1433:1433 -v /Users/dagrawal/Desktop/database/sql:/var/opt/mssql -m 4g -d microsoft/mssql-server-linux:2017-GA` 

Server Error 87(The parameter is incorrect.) occurred while opening file '/var/opt/mssql/data/master.mdf' to obtain configuration information at startup. An invalid startup option might have caused the error. Verify your startup options, and correct or remove them if necessary.

**Comment by jrutley** [comment]
I just got it too.

When I run it without specifying a volume, it runs fine, but specifying any sort of volume throws this error on a Mac host.

**Comment by CorstianBoerman** [comment]
Funny thing though, mssql manages to write the master database to the mounted volume... Go figure.

**Comment by pedershk** [comment]
I'm getting this too, with latest version of mssql-server-2017 for linux running under Docker for mac.

**Comment by chrisdone** [comment]
Me too, reproducing the same error.

**Comment by spriet2000** [comment]
yes here also

**Comment by twright-msft** [comment]
Volume mounting doesnt work on Docker for Mac.  I've added this to a known issues section on the Docker Hub page.  Lack of volume mounting on Docker for Mac is tracked here. https://github.com/Microsoft/mssql-docker/issues/12
