### ISSUE TITLE
No Backup to restore for WWI database

### ISSUE THREAD

**Issue by sqltj** [Microsoft/sql-server-samples#345]
There is not current updated backup to restore for the WWI database. The ReadMe points to an old github repo. This contains backups that are out of date with the version in this repo's BACPACs.

**Comment by jodebrui** [comment]
WWI backups can be found at the following location: https://github.com/Microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0

If you find a broken link in the documentation, please file a separate issue.
