### ISSUE TITLE
Error on SampleDb DROP IF EXISTS statement

### ISSUE THREAD

**Issue by WalterBuesoTBG** [Microsoft/sql-server-samples#351]
I'm getting an error when following the mssql tutorial (linked below). The error happens while dropping and creating the SampleDb. Error states: Incorrect Syntax near the keyword 'IF'.

here is the command from the tutorial: DROP DATABASE IF EXISTS [SampleDB]; CREATE DATABASE [SampleDB]

link: https://www.microsoft.com/en-us/sql-server/developer-get-started/csharp/win/step/2.html

**Comment by jodebrui** [comment]
Which version of SQL Server are you using?
The DROP IF EXISTS syntax was introduced in SQL Server 2016. For SQL Server 2014 and earlier you would use:

IF EXISTS (SELECT 1 FROM sys.databases WHERE NAME=N'SampleDB')
       DROP DATABASE [SampleDB];

CREATE DATABASE [SampleDB]


Thanks,
Jos

**Comment by trsekhar123** [comment]
Drop it exists works only with SQL server 2016 

Syntax is Drop object IF EXISTS objectname

**Comment by jodebrui** [comment]
No response from original poster

**Comment by vesko-k** [comment]
Yes MSSQL Server is 2012. I was wondering if the problem exists in other databases, MySql, SqLite or PostgreSQL.
