### ISSUE TITLE
No data inserted while installing 

### ISSUE THREAD

**Issue by rtwk** [Microsoft/sql-server-samples#368]
I have installed sql server 2017 developer edition on Ubuntu 16. Now when I try to install Adventureworks 
from a Windows 7 pc using SQL Server Management Studio following instructions given here, query executes, database and tables are created but no data inserted.

**Comment by rtwk** [comment]
Moreover, since .mdf and .log files are not available, I can't use RESTORE DATABASE coomand also.

**Comment by jodebrui** [comment]
When creating AdventureWorks from source, you need to ensure the data files are in a location available from SQL Server, as reflected in the installation script.

If you just want to install the sample and do not need source code, you can download database backups from the release page:
https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks

Considering sample databases, I would also recommend you take a look at WideWorldImporters, which is a more modern sample:
https://github.com/Microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0


Thanks,
Jos

**Comment by rtwk** [comment]
So, does that mean I have to create a smb share on Ubuntu which is available from Windows 7 (where SQL Management Studio is installed)? And can WideWorldImporters be installed in the same fashion AdventureWorks is installed?

**Comment by rtwk** [comment]
I get this error and this is the error stopping from loading data 
*** Loading Data
Msg 16202, Level 15, State 3, Line 1806
Keyword or statement option 'CODEPAGE' is not supported on the 'Linux' platform.
There must be a fix.

**Comment by rtwk** [comment]
Ok. So I removed CODEPAGE ='ACP' line and changed :setvar path and it worked. Thanks for your suuport  @jodebrui

**Comment by jodebrui** [comment]
The backup does not need to be installed on a share. It need to be placed in a location that is available to the server. In management studio, when you are selecting the backup location, it in fact shows the file system that is visible to the server, so any files local on the server will show up as local in the dialog.


Thanks,
Jos
