### ISSUE TITLE
mdf, ndf and log files do not exist

### ISSUE THREAD

**Issue by rtwk** [Microsoft/sql-server-samples#369]
While try to install Wide World Importers sample database v1.0 on Sql Server running on Ubuntu form various sql files, on the third sql file it asks for mdf, ndf and log files, which are not available neither in the repository or those are created in /var/opt/mssql/data/ which is the log location for sql server on Linux. How to get those files? Am I missing something?

**Comment by jodebrui** [comment]
When you download the sample database it is in backup format.
How are you trying to restore the backup? The tool you use for restoring the backup may ask for locations to place the database files. These locations do need to exist.

Which tool are you using, and which steps did you take that resulted in an error, and can you share the exact error message?


Thanks,
Jos

**Comment by jodebrui** [comment]
Closing since no response
