### ISSUE TITLE
Ubuntu 16.04 g++ & build-essential

### ISSUE THREAD

**Issue by neomobil** [Microsoft/sql-server-samples#371]
The example for ubuntu just works when the packages build-essential and g++ are installed.
Use: `sudo apt-get install g++ && sudo apt-get install build-essential`

**Comment by jodebrui** [comment]
Could you point me to the location that contains the issue?

**Comment by neomobil** [comment]
I'm sorry. I think this is not the correct repo. Originally I have followed the msphpsql repo and the issue was there.
