### ISSUE TITLE
Where are the SMO samples?

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/sql-server-samples#373]
This [page](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/link-to-programming-samples) links to a Codeplex page that links to here. I've downloaded a few things, but am not seeing the smo examples the page talks about.  

Are they somewhere else?

**Comment by jodebrui** [comment]
The page in the documentation was updated to remove the stale link. We currently do not have SMO samples on this repo.
