### ISSUE TITLE
Is there an AdventureWorks 2005?

### ISSUE THREAD

**Issue by meatballcoder** [Microsoft/sql-server-samples#374]
I only ask because the tutorial from March 2017 uses it.  For example, it calls for EmployeeID which is not in the current schema that I can find.  The comments indicate it is using 2005.  They give a link to CodePlex that is 1.9GB.  I was hoping you had it in .bak here.

https://docs.microsoft.com/en-us/sql/relational-databases/tables/lesson-1-1-examining-the-current-structure-of-the-employee-table

Thanks.

**Comment by jodebrui** [comment]
Thanks for catching this issue. I found a few problems with the linked lesson. An update to the lesson will be published in the next day or two.

**Comment by jodebrui** [comment]
Oh, and to be clear: there is no AdventureWorks2005 on this GitHub repo.
