### ISSUE TITLE
Analysis Services Tutorial SQL Server 2012.zip - where can I find this file?

### ISSUE THREAD

**Issue by krzysztofstawicki** [Microsoft/sql-server-samples#375]
Hello,
on page https://msdn.microsoft.com/en-us/library/fc475b25-cbb2-408a-901f-9299299538c5(v=sql.110) (Step 4)
there is a link to " Analysis Services Tutorial SQL Server 2012". I can't find file "Analysis Services Tutorial SQL Server 2012.zip".
I need this file to realize tutorial "Multidimensional Modeling (Adventure Works Tutorial)".

Could you check it?

Thanks.

Best regards,
Krzysztof Stawicki

**Comment by krzysztofstawicki** [comment]
Is it https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks-analysis-services/adventure-works-multidimensional-tutorial-projects.zip?

**Comment by Minewiskan** [comment]
@krzysztofstawicki  Sorry this reply is so late. It just made it to me. You have the right download.
