### ISSUE TITLE
Column Error in PROCEDURE [Integration].[GetStockItemUpdates]

### ISSUE THREAD

**Issue by StefanGrigat** [Microsoft/sql-server-samples#379]
Hi, 
there is a column mapping error in the PROCEDURE [Integration].[GetStockItemUpdates]. 
In Lines 70 and 74. 
The Insert Statement uses this column order:
[Is Chiller Stock], Barcode, **[Tax Rate]**, [Unit Price], [Recommended Retail Price],
and the select statement has
 si.IsChillerStock, si.Barcode, **si.LeadTimeDays**, si.UnitPrice, si.RecommendedRetailPrice,
So the Column "Tax Rate" ist filled with content of si.LeadTimeDays.
It should be:
si.IsChillerStock, si.Barcode, **si.TaxRate**, si.UnitPrice, si.RecommendedRetailPrice,

**Comment by StefanGrigat** [comment]
This should be the correct code in my opinion.
[ALTER PROCEDURE [Integration].[GetStockItemUpdates].txt](https://github.com/Microsoft/sql-server-samples/files/1825611/ALTER.PROCEDURE.Integration.GetStockItemUpdates.txt)

**Comment by jodebrui** [comment]
Thanks for catching this issue. I updated the stored procedure accordingly.
