### ISSUE TITLE
AdventureWorks2014 - Updated database/schema documentation?

### ISSUE THREAD

**Issue by capawaky** [Microsoft/sql-server-samples#380]
I installed the AW 2014 DB on my computer, but has the documentation been updated anywhere? 

I found documentation for the older version at https://technet.microsoft.com/en-us/library/ms124714(v=sql.100).aspx but it doesn't seem to apply to the 2014 version. For example, there is no "Contact" table in the "Persons" schema anymore.

**Comment by barbkess** [comment]
@capawaky : thanks for your inquiry.  We aren't planning to revise this older content for AdventureWorks at this time.  I added this issue to our backlog of content items.
