### ISSUE TITLE
No backupset selected to be restored issue

### ISSUE THREAD

**Issue by mattpannuzzo** [Microsoft/sql-server-samples#381]
Hi all,

I'm having issues trying to get the wide world imports DW running. I've tried searching for a solution but have not found anything yet and am hoping someone here can provide assistance.

Currently running SQL Server 2017 developer edition v17.6.

When trying to restore the database from the BAK file I get a message stating No backupset selected to be restored.
![wwidwerror](https://user-images.githubusercontent.com/37756926/37870176-188c5c9c-301b-11e8-8ef8-8c47450a1035.png)

I've also tried using the scripts to restore the database but still no luck.

RESTORE FILELISTONLY
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK'
 
RESTORE Database WideWorldImportersDW
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK'
WITH
MOVE 'WWI_Primary' TO 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\WideWorldImportersDW.mdf',
MOVE 'WWI_UserData' TO 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\WideWorldImportersDW_UserData.ndf',
MOVE 'WWI_Log' TO 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\WideWorldImportersDW.ldf',
MOVE 'WWIDW_InMemory_Data_1' TO 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\WideWorldImportersDW_InMemory_Data_1',
RECOVERY, STATS =10

I then get the following error message:
Msg 3241, Level 16, State 0, Line 1
The media family on device 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK' is incorrectly formed. SQL Server cannot process this media family.
Msg 3013, Level 16, State 1, Line 1
RESTORE FILELIST is terminating abnormally.
Msg 3241, Level 16, State 0, Line 4
The media family on device 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK' is incorrectly formed. SQL Server cannot process this media family.
Msg 3013, Level 16, State 1, Line 4
RESTORE DATABASE is terminating abnormally.

I've then also tried the following scripts but also receive errors:

RESTORE VERIFYONLY
from disk = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK'

Error:
Msg 3241, Level 16, State 0, Line 15
The media family on device 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK' is incorrectly formed. SQL Server cannot process this media family.
Msg 3013, Level 16, State 1, Line 15
VERIFY DATABASE is terminating abnormally.

RESTORE headeronly
from disk = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK'

Error:
Msg 3241, Level 16, State 0, Line 19
The media family on device 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\WideWorldImportersDW-Full.BAK' is incorrectly formed. SQL Server cannot process this media family.
Msg 3013, Level 16, State 1, Line 19
RESTORE HEADERONLY is terminating abnormally.

Are the files corrupt or could the errors be due to using SQL Server 2017 as opposed to 2016?

Help appreciated.
Thanks
- Matt

**Comment by jodebrui** [comment]
>> SQL Server 2017 developer edition v17.6.

I assume you are referring to the version of Management Studio, since 17.6 is not a valid version number for SQL Server?

The location of the backup seems to indicate you are in fact running SQL Server 2012, not 2017. The WideWorldImporters backups were created using SQL Server 2016, and restoring a backup created using a later version of SQL Server is not supported.
You can confirm the version of SQL Server by executing the query:
                SELECT @@version


Thanks,
Jos

**Comment by jodebrui** [comment]
Confirmed that this error is expected when attempting to restore a database to a down-level server. WideWorldImporters is only supported for SQL Server 2016 or higher.

**Comment by mattpannuzzo** [comment]
Thanks.
I do have both 2012 and 2017 installed on my machine.

I've run @@VERSION on SSMS 2017 and it is returning Microsoft SQL Server 2012. 

Should I remove 2012 completely?

**Comment by mattpannuzzo** [comment]
All fixed.

Only had the 2017 GUI installed basically. I've now upgraded the instance from 2012 to 2017 and the have successfully restored the WWI database.
