### ISSUE TITLE
Producing Data

### ISSUE THREAD

**Issue by UsamaAshraf82** [Microsoft/sql-server-samples#387]
Can I Produce Data From 2008-2012 In Wide World Importers OLTP Database

If Yes ,then How

I have Already Seen This
[https://docs.microsoft.com/en-us/sql/sample/world-wide-importers/data-generation](url)

and Execute This
```
EXECUTE DataLoadSimulation.PopulateDataToCurrentDate
@AverageNumberOfCustomerOrdersPerDay = 60,
@SaturdayPercentageOfNormalWorkDay = 50,
@SundayPercentageOfNormalWorkDay = 0,
@IsSilentMode = 1,
@AreDatesPrinted = 1;
```
Basically I need Some Historic  data like 10 Year Data but by the
 ` DataLoadSimulation.PopulateDataToCurrentDate` 
It will Generate Data From 2013-1-1 to Current Date Which is not sufficient

**Comment by jodebrui** [comment]
The procedure PopulateDataToCurrentDate internally calls the stored procedure [DataLoadSimulation].[DailyProcessToCreateHistory], which accepts a start and end date. By picking a start date in 2008 and an end date in 2012 you can generate historical data for that period. The example script below generates a month's worth of data in 2008.
In addition, if you are deploying the database from source code using SSDT, you can tweak the dates in the corresponding procedure call in Script.PostDeployment1.sql to suit your needs.


EXEC DataLoadSimulation.DailyProcessToCreateHistory 
    @StartDate = '20080101',
    @EndDate = '20080201',
    @AverageNumberOfCustomerOrdersPerDay = 60,
    @SaturdayPercentageOfNormalWorkDay = 25,
    @SundayPercentageOfNormalWorkDay = 0,
    @UpdateCustomFields = 1,
    @IsSilentMode = 0,
    @AreDatesPrinted = 1;
GO

**Comment by jodebrui** [comment]
Actually, I just tested this scenario. Creating data older than current data may cause inconsistencies in the system versioning.
Therefore, the recommendation is to deploy the database from source, after modifying Script.PostDeployment1.sql to use the date range you are interested in.

Instructions for deploying from source code are here: https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/wide-world-importers/wwi-ssdt

**Comment by UsamaAshraf82** [comment]
Thanks
