### ISSUE TITLE
ML Services: SSMS Custom Reports - R Services - Script.rdl not found.

### ISSUE THREAD

**Issue by hfleitas** [Microsoft/sql-server-samples#392]
## Issue

This is a bug or unexpected behaviour. Its simple to fix by just editing 3 xml tags. 
ReportName (qty 1)
Parameter Name (qty 2)

## Bug Report

File: ...\ssms-custom-reports\R Services - Script.rdl was not found.

### General Troubleshooting steps

Open ML Services - Extended Events.rdl, click View SQL script. See Error.
Open ML Services - Packages.rdl, click View SQL script. See Error.
Open ML Services - Resource Usage.rdl, click View SQL script. See Error.

### Version Information
 - Operating System (Name|Version): Win10
 - SSMS: 17.6
 - SQL Server (Edition|Version): 2017 Dev - 14.0.3022.28

### Steps to Reproduce
1. Clone this repo to local drive.
2. Open SSMS, Connect to DB Engine, right click instance, Reports, Custom Reports...
Browse to cloned repo folder add each one. ie.
C:\Users\hfleitas\Source\Repos\sql-server-samples\samples\features\machine-learning-services\ssms-custom-reports\
3. Run the 3 reports listed above and click View SQL Script. 

## Additional information    
Open the 3 rdls in notepadd, find, replace, save, commit, sync, push.

Erroneous:
R Services - Script
SQLR_ReportName
SQLR_Script

Corrected:
ML Services - Script
SQLML_ReportName
SQLML_Script

**Comment by uc-msft** [comment]
Thanks for reporting the issue. I fixed it.
