### ISSUE TITLE
Sql Server 2017 does not output chat(10) or char(13)

### ISSUE THREAD

**Issue by FlavioDiasPs** [Microsoft/sql-server-samples#407]
Hi guys,

I just migrated from sql server 2014 to sql server 2017.

What is happening is that SQL Server 2017 is not returning the following code as expected. 

`select 'hi' + char(10) + char(13) + 'people'`

I am not getting any line break.

Does anyone know about it?

**Comment by FlavioDiasPs** [comment]
The MSSMS 2017

Microsoft SQL Server Management Studio	14.0.17213.0

**Comment by fmms** [comment]
@FlavioDiasPs have a look at https://blog.sqlauthority.com/2016/06/03/sql-server-maintain-carriage-return-enter-key-ssms-2016-copy-paste/

**Comment by jodebrui** [comment]
The mentioned blog post shows how to maintain the line breaks. You can also use text, rather than grid results. Just click Query->Results To->Results To Text.

**Comment by FlavioDiasPs** [comment]
Thx guys!

It worked for me.
