### ISSUE TITLE
Missing Custom Transformation Component Example

### ISSUE THREAD

**Issue by salchichongallo** [Microsoft/sql-server-samples#409]
Hi! I'm looking for the [Change Case Component Sample](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms160910%28v%3dsql.90%29) or a newer version, but I couldn't find it.

**Comment by jodebrui** [comment]
As noted on the linked documentation page, this content has been retired. SQL Server 2005 has been out of support for a long time.

**Comment by salchichongallo** [comment]
And a newer version?
