### ISSUE TITLE
Request for new SQL Server feature to Microsoft for backup / restore - rollback from log backup

### ISSUE THREAD

**Issue by MironAtHome** [Microsoft/sql-server-samples#410]
Microsoft connect is closed... so, using Microsoft's GitHub to request new features.

Our company currently working on new product with 3rd party vendor. The application, provided by 3rd party vendor, that is the fundamental to company business uses Microsoft SQL Server database. The role of the database in the application is so much of a sustenance and working, that it's not worth discussing.

As time advanced forward we had to concentrate our efforts on advancing this application to provide for business event of bringing online start of new venue of the business. I think everyone, who had ever worked on a complex product with software application at its core understands how fast this entire enterprise moves forward. So, there isn't all that much time to extensively use various pre - production environments, which are available and work as expected. So, the thrust of team effort falls on developer instance, which at the moment services as a "production in works". There is a log backup in progress continuously taking backup in the background every 15 minutes. However, the backups accumulate continuously and replaying those takes time. Which is the most scarce currency of all. At times an errant operation, which in dev is normal, causes entire enterprise to stutter. Replaying backups forward is not acceptable due to the duration of time.

The new feature requested here is as following: "please provide for new type of "restore log" operation - the "rollback log"". Since in fully logged database, the database taking log backup(s) continuously provides unbreakable chain of LSN's it is technically feasible. that an LSN of log backup is available in the database at its current state. So, a rollback to this LSN is feasible technically and can ( potentially ) provide for near instantaneous recovery to last good known state.

The win is two fold
1. instead of rolling forward some hundreds of log backups all is needed is to replay 1 - 3 log rollback operation files, winning hours and hours in time, saving the most demanding part - initial full restore.
2. the restore is not an innocuous operation in an of itself. It changes certain database properties within database and without, that need to be captured and restored to initial ( pre - restore ) state upon restore completion. The rollback operation is safe from these pitfalls and reduces operational load on DBA, which can be pulled into numerous projects, tasks and streams of thought concurrently.
3. with proper implementation this feature can be implemented in such a away, that an Always - On ( or mirrored ) database copy, can perform even better, friendlier to user sequence

On mirrored copy
1. create database snapshot
2. rollback to desired log backup ( an off - line step )
3. bring live database on - line
4. perform delta between snapshot and live copy, apply desired changes, that user wants to retain
5. apply changes identified in step 4 fail over to corrected database copy, resume on - line operation
6. let the new mirror / read - only partners catch up to changes, as if those were on - line activities

at this moment mirrored or always - on database partners fully in sync and ready to continue

**Comment by jodebrui** [comment]
Please use the following forum for SQL Server feedback and suggestions. This GitHub repository is specifically for SQL Server and Azure SQL samples, not the products and services themselves.

https://feedback.azure.com/forums/908035-sql-server

**Comment by MironAtHome** [comment]
The real fun would be to replay this way some slow running transaction with various options on a petabyte sized database... A petabyte sized database suddenly becomes a lot more manageable at a fraction of cost ( if you wanted a good example )
