### ISSUE TITLE
Repackage Microsoft.SqlServer.Compact

### ISSUE THREAD

**Issue by kasper3** [Microsoft/sql-server-samples#413]
I am aware the Microsoft.SqlServer.Compact is not developed anymore. However, can it be repackaged with the new nuget format (especially renaming `NativeBinaries\amd64, x86` directories to `runtimes -> win-x86, win-64` and removing `tools` directory from package), so we don't have to explicitly run `packages\Microsoft.SqlServer.Compact\4.0.8876.1\tools\Install.ps1`, or copy the native binaries in post build step?

In addition to lowercase package name (which `nuget pack`, `dotnet pack` use), the package with mixed (native & managed) assets should have structure summarized in:
https://stackoverflow.com/questions/40104838/automatic-native-and-managed-dlls-extracting-from-nuget-package/40652794#40652794 and official documentation is at https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks.

**Comment by jodebrui** [comment]
Hi,

This GitHub repo is specifically for samples. It is not used for tracking product feedback. Feel free to post your feedback on the SQL Server feedback forum: https://feedback.azure.com/forums/908035-sql-server
