### ISSUE TITLE
Tag adventureworks2014 is missing

### ISSUE THREAD

**Issue by nschonni** [microsoft/sql-server-samples#416]
It's referenced over on https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/analysis-services/analysis-services-samples.md as https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks2014
Possible the tag never existed, but I do see 2008R2 and 2016 tags.

**Comment by dzsquared** [comment]
Please file this issue on the docs article
