### ISSUE TITLE
Invalid date column names in wwi-ssasmd

### ISSUE THREAD

**Issue by korompaiistvan** [microsoft/sql-server-samples#423]
Admittedly newbie here, possibly missing something trivial.

My initial deploy of wwi-ssasmd from SSDT failed due to authentication issues. It seems though that certain dimensions are pointing to invalid date columns in the WorldWideImportersDW database.
When processing the 'Date' dimension the following error is thrown (among others but those seem to be a result of this one):
`OLE DB error: OLE DB or ODBC error: Invalid column name 'Year Key'.; 42S22.`
SQL Query:
```
SELECT 
DISTINCT
[Dimension_Date].[Year Key] AS [Dimension_DateYear_x0020_Key0_0],[Dimension_Date].[Calendar Year Label] AS [Dimension_DateCalendar_x0020_Year_x0020_Label0_1]
FROM [Dimension].[Date] AS [Dimension_Date]
```

Yet the DW does not have a Year Key column, as shown on the below screenshot.
![image](https://user-images.githubusercontent.com/36007115/42330074-99e42214-8072-11e8-87bc-ba83daac2936.png)

Both resources have been obtained on 2018 July 4th from respectice GitHub links. ([.bak file for the DW](https://github.com/Microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0), [.sln for the ssasmd](https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/wide-world-importers/wwi-ssasmd))

**Comment by arcanecode** [comment]
If you got the BAK file from the page that reads "Wide World Importers sample database v1.0", the database there is out of sync with the SSASMD Project which was built on version 2.0 of the data warehouse database. In version 2.0 of the DW, the date table got a major revision to support many types of date scenarios. 

I will see about raising an issue to get new ZIPs / BAKs created based on the 2.0 version of WWI.

For now you could download the database and SSIS samples from the 2.0 page and deploy from the Visual Studio projects.

**Comment by mattturner86** [comment]
I've just struggled with this same issue and came across this issue.
It'd be good to get the release page for the database sample updated. I installed the sample database from the release page [here](https://github.com/Microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0)

**Comment by robotpukeko** [comment]
How can we source the updated version of the database, as the currently provided 1.0 is still broken? We've looked for a branch or release for 2.0, but can't find it anywhere.

**Comment by AbubakerShekhani** [comment]
Can you please share the updated v2.0 of the WWI DW?

**Comment by JimmyEmmy** [comment]
wwi-ssasmd.sln still out of synch with WideWorldImportersDW.  Latest availavle samples sln still 1.0
How can Microsofts flagship sample WideWorldImporters still be broken ?
