### ISSUE TITLE
The object 'Colors_Archive' is enabled with data compression or vardecimal storage format. Data compression and vardecimal storage format are only supported on SQL Server Enterprise Edition.

### ISSUE THREAD

**Issue by DerWilk** [Microsoft/sql-server-samples#45]
When I try to restore WideWorldImporters-Standard.bak on my virtual machine with Microsoft SQL Server Standard (64-bit) 13.0.1601.5 I get two messages in the Windows Application log of the Eventviewer:

Database 'WideWorldImporters' cannot be started in this edition of SQL Server because part or all of object 'Colors_Archive' is enabled with data compression or vardecimal storage format. Data compression and vardecimal storage format are only supported on SQL Server Enterprise Edition.

and

Database 'WideWorldImporters' cannot be started because some of the database functionality is not available in the current edition of SQL Server.

And now I'm a bit disappointed.

With regards,

Johan van der Wilk

**Comment by jodebrui** [comment]
Thanks for the feedback. We fixed the issue – the WideWorldImporters-Standard.bak currently up on GitHub can restore successfully to a Standard Edition instance.

--
Jos de Bruijn

**Comment by DerWilk** [comment]
Hallo Jos,

I'm now at set 6-wwi-data-simulation.sql and everthing works fine.

Thank you very much for the quick fix.

Johan van der Wilk
