### ISSUE TITLE
AdventureWorks2012.bak

### ISSUE THREAD

**Issue by aydot24** [microsoft/sql-server-samples#453]
Hi guys, please I need your help. I have been trying to download Adventureworks 2012.bak but it keeps downloading into PDF. Has anyone experienced such.

**Comment by MikeRayMSFT** [comment]
Are you working from here: https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks2012 

If not, try that.

Thanks

**Comment by aydot24** [comment]
Dear Mike, thank you so much for the swift response. I wasn't using the link you provided. I have used the link and I have been able to download the file but still trying to attach it to the database as it's coming up with an error.

**Comment by 19Aziza68** [comment]
Hi Guys, I have tried to open  Adventureworks 2012.bak  but it keeps open blanco in my internet explorer, 
I ma using windows 10 on MAC  
please if any one can help.
