### ISSUE TITLE
instawdbdw.sql failures

### ISSUE THREAD

**Issue by Liturgist** [Microsoft/sql-server-samples#461]
When I open instawdbdw.sql in SSMS and run it, there are many errors. Should I just start editing and try to correct these? I doubt if I can. Please advise. Thanks.

Msg 102, Level 15, State 1, Line 39
Incorrect syntax near 'C:\Samples\AdventureWorksDW\'.
Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64) 
	Jul 21 2018 07:47:45 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 17134: )

 
Started - 2018-10-18 19:59:10.980
 
*** Dropping Database
Msg 102, Level 15, State 1, Line 80
Incorrect syntax near '$'.
 
*** Creating Database
Msg 102, Level 15, State 1, Line 94
Incorrect syntax near '$'.

**Comment by Uggywuggy** [comment]
I found same problem today - did you find a way round it?

**Comment by Liturgist** [comment]
No answers. Still a problem.

> I found same problem today - did you find a way round it?

**Comment by Liturgist** [comment]
I was successful downloading from and using the process described at [docs.microsoft.com](https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-2017)

**Comment by GuitarHero1969** [comment]
Is it possible to run this file without SSMS ?
I have just downloaded VS2017 over 20GB !!! and it has sql server stuff, so I would like, if possible to use the sql features in Visual Studio without having to download SSMS aswell !
