### ISSUE TITLE
Error running Northwind & Pubs database Query

### ISSUE THREAD

**Issue by ShyamSundarShankar** [Microsoft/sql-server-samples#484]
Thanks, @douglaslMS!
Copied the query from the databases folder and ran the Query and got the below Error Message and the database has been Created. I'm using **SSMS v17.8** in **Windows 10 x64**. 
```
Msg 2812, Level 16, State 62, Line 56
Could not find stored procedure 'sp_dboption'.
```

**Comment by douglaslMS** [comment]
@ShyamSundarShankar Thank you for reminding me about the deprecated system stored procedure. I got that error myself but forgot to fix it before copying the scripts to this new location. I'll do that today.

**Comment by douglaslMS** [comment]
@ShyamSundarShankar I see that this issue has been fixed very recently by another user, and the scripts in the repo are already updated.

**Comment by ShyamSundarShankar** [comment]
Thanks..
