### ISSUE TITLE
SQL Managed Instance Prepare Subnet script Incorrect

### ISSUE THREAD

**Issue by adminnz** [microsoft/sql-server-samples#516]
If you run the SQL Managed Instance Prepare Subnet script against a vnet & subnet which matches the [network requirements](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-connectivity-architecture#network-requirements).
It will display warnings for:

> [NSG] -Allow outbound TCP traffic on port 80
> [NSG] -Allow outbound TCP traffic on port 443
> [NSG] -Allow outbound TCP traffic on port 12000

Even though the network security group has these ports/direction/protocol allowed.

To see if I had somehow missed something, I have another VNET & subnet in a separate subscription that was created automatically by the SQL Managed Instance portal wizard (i.e. not manually created) and it produces the same warnings (in fact it also has warnings about the Route Table not having 0.0.0.0/0 -> Internet route defined).

**Comment by Turil** [comment]
This still is an issue, please fix.
There is also conflicting information for Network Security Group settings.
Specifically the "management" outbound rule: In the official documentation (https://docs.microsoft.com/de-de/azure/sql-database/sql-database-managed-instance-connectivity-architecture#network-requirements) it says the destination should be "AzureCloud" but the script will output a warning / error message and sets the rule with destination "Any".

**Comment by jabbera** [comment]
Submitted a PR for this issue
