### ISSUE TITLE
Create a localdb edition?

### ISSUE THREAD

**Issue by julielerman** [Microsoft/sql-server-samples#56]
any chance of creating a version I can use with localdb? I believe the "WWIDW_InMemory_Data_1" file group is preventing me from restoring this on a machine with VS2015 and a SQL Server 2016 localdb but not full install.
Thanks

Thought I would relay what I've been doing and what results I got that drove me to this conclusion.

I downloaded WideWorldImportersDW-Full.bak (hoping for the simplest one...did I choose well?)

I looked at the file list with : 
`RESTORE FILELISTONLY FROM Disk= 'C:\Users\Julie\Downloads\WideWorldImportersDW-Full.bak'
`
Then tried to restore this way:

```
RESTORE DATABASE [WideWorldImporters]
FROM Disk= 'C:\Users\Julie\Downloads\WideWorldImportersDW-Full.bak'
     WITH MOVE 'WWI_Primary' TO 'D:\databases\wwwimporters.mdf',  
   MOVE 'WWI_Log' TO 'D:\databases\wwwimporters.ldf';  

```
resulting error is:
The database cannot be started in this edition of SQL Server because it contains a MEMORY_OPTIMIZED_DATA filegroup. See Books Online for more details on feature support in different SQL Server editions.

Then I tried to just restore the primary file 

RESTORE DATABASE [WideWorldImporters]
FILE='WWI_Primary'
 FROM Disk= 'C:\Users\Julie\Downloads\WideWorldImportersDW-Full.bak'
     WITH MOVE 'WWI_Primary' TO 'D:\databases\wwwimporters.mdf'

And got another memory data related error:
A BACKUP or RESTORE DATABASE statement that includes the primary filegroup must include the MEMORY_OPTIMIZED_DATA filegroup, and vice versa.

**Comment by jodebrui** [comment]
We'll look into it. The initial release is targeting full SQL Server installations, as well as Azure SQL Database. Note that the bacpac versions have a slightly different configuration of the filegroups, so importing those might work.
Note that we are planning a Database project version. That will give some more flexibility.

**Comment by julielerman** [comment]
Thanks. I was adding details while you were responding but based on your response, I think I did, indeed, reach the right conclusion after all. :)

**Comment by jodebrui** [comment]
The Full version of the sample DBs only works with SQL Server Enterprise/Eval/Developer. You could try the Standard Edition version.
