### ISSUE TITLE
no matches for kind "SqlServer" in version "mssql.microsoft.com/v1"

### ISSUE THREAD

**Issue by enriquecatala** [microsoft/sql-server-samples#563]
when I try to deploy the Availability Group SQL Server 2019 demo over AKS, I get this error

_**kubectl apply -f .\sqlserver.yaml -n ag1**
service/mssql1 unchanged
service/mssql2 unchanged
service/mssql3 unchanged
unable to recognize ".\\sqlserver.yaml": n**o matches for kind "SqlServer" in version "mssql.microsoft.com/v1"**
unable to recognize ".\\sqlserver.yaml": no matches for kind "SqlServer" in version "mssql.microsoft.com/v1"
unable to recognize ".\\sqlserver.yaml": no matches for kind "SqlServer" in version "mssql.microsoft.com/v1"_

I have this version of AKS deployed:
_Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}_

I´m using the default values found here: https://github.com/microsoft/sql-server-samples/tree/master/samples/features/high%20availability/Kubernetes/sample-manifest-files

**Comment by NileshGule** [comment]
@enriquecatala did you deploy the operator and the sapassword as secret in your AKS environment? Those two are prequisites before the sqlserver related CRDs can be deployed. I was able to get the SQL Server 2019 running using the steps mentioned in the docs

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-kubernetes-deploy?view=sql-server-ver15

**Comment by enriquecatala** [comment]
thank you nileshGule, you are right. i had a typo in the secret :)

**Comment by enriquecatala** [comment]
it was related to a typo in the secret. not a script problem but mine
