### ISSUE TITLE
high availability/Linux/Ansible Playbook - Certifcate Issue

### ISSUE THREAD

**Issue by leesedd** [microsoft/sql-server-samples#589]
Hi, 
I'm trying to use the Ansible playbook to build a Linux cluster.  I'm having an issue with the creating certificates part.

If I build a cluster manually, Once the SQL instances are installed, I would create a certificate on each, back this up to a .cer file then copy this to the other nodes and use it to create a certificate on each node. Each node ends up with a certificate for itself and a certificate for each of the other nodes in the cluster so the AG endpoints can all communicate with each other.

This playbook seems to presume that you have a public and private key saved in a share that is then copied to each node and used to create a certificate.

Within play.yml you set the path of where the public and private key should be accessible with
dbm_cert_pub
dbm_cert_priv

These are then copied in the 'mssql-server-ha' role to the SQL install location and later used to create a certificate on each node within SQL Server   

- name: copy DBM cert public key
  copy:
    src: "{{ dbm_cert_pub }}"
    dest: "/var/opt/mssql/data/{{ dbm_cert_pub_target }}"
    owner: mssql
    group: mssql
    mode: 0444

- name: copy DBM cert private key
  copy:
    src: "{{ dbm_cert_priv }}"
    dest: "/var/opt/mssql/data/{{ dbm_cert_priv_target }}"
    owner: mssql
    group: mssql
    mode: 0400 

Am I missing something? I cant seem to find any documentation on creating public and private keys to be used to create certificates before the SQL instances have been installed ?
Or should the keys be getting created as part of the playbook somewhere that I have not found?

Thanks,

Lee.

**Comment by leesedd** [comment]
This can be closed.  I figured out how to create a certificate .cer and .pvt file that can be saved in the share and used on all nodes.

**Comment by ajith2234** [comment]
hi @leesedd 
Could you share the solution which you have used to fix the issue?

Thank you
