### ISSUE TITLE
SQLAssessment API SqlServer.Database.QueryStoreOn and "[12.0,)"

### ISSUE THREAD

**Issue by williamadba** [microsoft/sql-server-samples#606]
sql-server-samples/samples/manage/sql-assessment-api/

I'm trying to figure out why the Query Store check SqlServer.Database.QueryStoreOn doesn't incorrectly return a finding to enable the Query Store on databases in SQL 2014. I know Query Store wasn't introduced until SQL 2016, but the check appears to use "[12.0,)", apparently meaning "[Applies to SQL Server 2014 and higher](https://github.com/microsoft/sql-server-samples/tree/master/samples/manage/sql-assessment-api)", and the value returned by [sys].[databases].is_query_store_on is 0. Is there some other precedence or layer preventing this assessment recommendation from being found for SQL 2014 databases?

**Comment by msalexprotsenko** [comment]
@williamadba thanks for reporting this. It's definitely an issue, and it's already a known one—we caught it right after the release.  It will be fixed in the next release.

**Comment by williamadba** [comment]
Cool. What's the fix? Designing my own checks and would like to follow suit.

**Comment by msalexprotsenko** [comment]
In the next release, we will just replace "[12.0,)" with "[13.0,)" in this check. If you need a workaround right now, you can create a customization file containing the following:
{ 
	"checks":[
        {
            "id": "SqlServer.Database.QueryStoreOn",
            "target":{
                "type": "Database",
                "version": "[13.0,)",
                "platform": "Windows",
                "name": { "not": "/^(master|tempdb)$/" }
            }
        }
	] 
} 
Save it as, for example, QueryStore_fix.json.
Then run the cmdlet with -configuration parameter. 
Invoke-SqlAssessment -configuration "C:\SQLAssessment\QueryStore_fix.json"

**Comment by williamadba** [comment]
Awesome, thanks for that, based on what I understand about the syntax that was my guess as well, was just throw off by the existing samples. Thanks!

**Comment by msalexprotsenko** [comment]
@williamadba no problem.

I also added QueryStoreCheck_fix.json to the SQL Assessment samples folder.
