### ISSUE TITLE
ubuntu kubeadm deployment should mention Storage Class question

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [microsoft/sql-server-samples#610]
This is about sql-server-samples/samples/features/sql-big-data-cluster/deployment/kubeadm/ubuntu/

Hi,

Readme should mention the Storage Class step when deploying using "kubeadm-dev-test" profile, especially since previous steps/scripts  precisely provisioned the Storage Namespace to be used =)

Namely, kubeadm create will prompt with the following : 
`				Kubernetes Storage Class
				- Config Path: spec.storage.data.className
				- Description: This indicates the name of the Kubernetes Storage Class to use. You must pre-provision the storage class and the persistent volumes or you can use a built in storage class if the platform you are deploying provides this capability.
				- Please provide a value:`

And I _suspect_ that we're supposed to enter "local-storage" as per what the local-storage-provisioner.yaml script created ("name: local-storage")

**Comment by shaximinion** [comment]
I have the exact same issue: https://github.com/microsoft/sql-server-samples/issues/651

It's a bit worrying no one has helped you since the 14th of August! :-1: 

I will try following the guide without the scripts and see if it works: https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-with-kubeadm?view=sqlallproducts-allversions

**Comment by Guillaume-Fourrat** [comment]
> 
> 
> I have the exact same issue: #651
> 
> It's a bit worrying no one has helped you since the 14th of August! 👎
> 
> I will try following the guide without the scripts and see if it works: https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-with-kubeadm?view=sqlallproducts-allversions

Hi Shaximinion, I've replied to your issue #651. To answer the aspects more specific to your statement above : 
1° wrt lack of help, well I discovered since that raising *issues* puts them in the same global basket as *all* SQL Samples (not just BDC, which arguably is a slightly hotter topic right now). Usually, PullRequests work better (when they are possible) as they're strongly tied to the specific content (in fact I think I'll PR this right now as I'm now confident about how things should be). But if it's an Issue you need about those scripts, you can @mention me and I'll try to help.
2° Using the doc will work too, but you will have to discover several subtopics, like provisioning your storage class yourself etc, which the samples here precisely try to abstract.
I would recommend to use the samples here until you get your first BDC running, at which point you may start to discover more advanced topics.

We've been working on testing and making those scripts more reliable in the past few weeks, so they _should_ work for you =). If not, again you can @mention me in any issue you create ;).

Happy discovery !

**Comment by Guillaume-Fourrat** [comment]
Materialized in PR #657 .
Closing issue.
