### ISSUE TITLE
Attempting to set Partial Containment results in Stack Dump

### ISSUE THREAD

**Issue by paschott** [Microsoft/sql-server-samples#66]
Running on SQL 2016 Developer edition. Attempting to set the database to Partial Containment results in a stack dump.

**Comment by jodebrui** [comment]
Hi Peter,

Did you file a Connect item for this? That would help us track the issue.

Which database are you attempting to configure? Is it one of the sample databases?

Can you also include the exact error message you are seeing, the stack dump, as well as the minidump (if any)?


Thanks,
Jos

**Comment by jodebrui** [comment]
I just managed to reproduce the issue using the WideWorldImporters-Standard database.
We are investigating.

From: Jos de Bruijn
Sent: Thursday, July 7, 2016 8:47 AM
To: 'Microsoft/sql-server-samples' <reply@reply.github.com>; Microsoft/sql-server-samples <sql-server-samples@noreply.github.com>
Subject: RE: [Microsoft/sql-server-samples] Attempting to set Partial Containment results in Stack Dump (#66)

Hi Peter,

Did you file a Connect item for this? That would help us track the issue.

Which database are you attempting to configure? Is it one of the sample databases?

Can you also include the exact error message you are seeing, the stack dump, as well as the minidump (if any)?


Thanks,
Jos

**Comment by jodebrui** [comment]
We fixed the issue in our main code base. The fix should be in an upcoming CU.


Thanks,
Jos

**Comment by jodebrui** [comment]
The fix is going to be in SQL Server 2016 RTM CU4 and SP1 CU1.
