### ISSUE TITLE
Internet explorer in containers

### ISSUE THREAD

**Issue by clicman** [Microsoft/sql-server-samples#72]
Hi! Sorry for writing issue here. Don't found the place to file to.
For test automation purposes it will be great to see windows containers with internet explorer onboard.
As I can see there is on IE on windowsservercore images.

How do I cn solve this problem?

**Comment by perrysk-msft** [comment]
Hi - 

Please post this question to the Windows container forum for further assistance?
https://social.msdn.microsoft.com/forums/en-us/home?forum=windowscontainers

Thanks.
