### ISSUE TITLE
Failed to start service 'SQL Server (SQLEXPRESS)

### ISSUE THREAD

**Issue by Revolution1** [Microsoft/sql-server-samples#73]
I created the container with docker-compose 1.0

Here is the yaml:

```yaml
mssql-server-2014-express-windows:
  environment:
    sa_password: '12345678'
  image: microsoft/mssql-server-2014-express-windows:latest
  labels: {}
  ports:
  - 1433:1433
  restart: unless-stopped
```

Here is the container's log

```
PS C:\Users\cai> docker logs 9d69a4c4f4c7
docker : start-service : Failed to start service 'SQL Server (SQLEXPRESS) 
At line:1 char:1
+ docker logs 9d69a4c4f4c7
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (start-service :...r (SQLEXPRESS) :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
(MSSQL$SQLEXPRESS)'.
At C:\start.ps1:9 char:1
+ start-service MSSQL`$SQLEXPRESS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl 
   ler:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands 
   .StartServiceCommand
 
Invoke-Sqlcmd : A network-related or instance-specific error occurred while 
establishing a connection to SQL Server. The server was not found or was not 
accessible. Verify that the instance name is correct and that SQL Server is 
configured to allow remote connections. (provider: SQL Network Interfaces, 
error: 26 - Error Locating Server/Instance Specified)
At C:\start.ps1:14 char:5
+     Invoke-Sqlcmd -Query $sqlcmd -ServerInstance ".\SQLEXPRESS"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlExcept 
   ion
    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management. 
   PowerShell.GetScriptCommand
 
Invoke-Sqlcmd : 
At C:\start.ps1:14 char:5
+     Invoke-Sqlcmd -Query $sqlcmd -ServerInstance ".\SQLEXPRESS"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserExceptio 
   n
    + FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Ma 
   nagement.PowerShell.GetScriptCommand
 
start-service : Failed to start service 'SQL Server (SQLEXPRESS) 
(MSSQL$SQLEXPRESS)'.
At C:\start.ps1:9 char:1
+ start-service MSSQL`$SQLEXPRESS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl 
   ler:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands 
   .StartServiceCommand
```

And the docker ps shows it still running

```
PS C:\Users\cai> docker ps
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS  
            PORTS                    NAMES
9d69a4c4f4c7        microsoft/mssql-server-2014-express-windows:latest   "cmd /S /C 'powershel"   23 minutes ago      Up 6 min
utes        0.0.0.0:1433->1433/tcp   sqlserver_mssql-server-2014-express-windows_1
```

need help

**Comment by perrysk-msft** [comment]
Thanks for reporitng this issue. A couple of questions that will assist us in reproducing and troubleshooting this issue in our enviroment: 

1. Can you check if any Windows updates are available? There are some issues that are fixed in the update rollups for Windows Server 2015 Technical Preview such as https://support.microsoft.com/en-us/kb/3163016

2. Could you please provide the Image Id of the Windows Server Core image that you are using? You should be able to get this by running the "docker images" command. 

3. Could you please tell us a bit about your environment? Are you trying this on a VM or on a local server?  

Finally, there is a known issue that requires restarting the server after multiple builds/runs of the Docker image. The fix for this issue will be part of the upcoming Windows Server 2016 RTM (later this year). Not sure if this applies to this issue, but could you stop the container, restart the server and run the container again to see if that resolves the issue? 

Thanks.

**Comment by Revolution1** [comment]
```
REPOSITORY                                    TAG                 IMAGE ID      
      CREATED             SIZE
swarm-win                                     latest              7aa7faaf1061  
      33 hours ago        9.382 GB
microsoft/mssql-server-2014-express-windows   latest              e807ab1d8cef  
      5 weeks ago         11.71 GB
windowsservercore                             10.0.14300.1000     5bc36a335344  
      9 weeks ago         9.354 GB
windowsservercore                             latest              5bc36a335344  
      9 weeks ago         9.354 GB
nanoserver                                    10.0.14300.1016     3f5112ddd185  
      9 weeks ago         810.2 MB
nanoserver                                    latest              3f5112ddd185  
      9 weeks ago         810.2 MB
microsoft/dotnet35                            latest              d9aa93e5e8f8  
      11 weeks ago        10.18 GB
microsoft/iis                                 latest              c26f4ceb81db  
      11 weeks ago        9.49 GB
microsoft/sample-python                       windowsservercore   0f7977bc4a43  
      11 weeks ago        9.565 GB

```

![image](https://cloud.githubusercontent.com/assets/3241438/17045193/10bc38aa-4ffa-11e6-921a-cc3c110e595e.png)

![image](https://cloud.githubusercontent.com/assets/3241438/17045567/061314fc-4ffd-11e6-9d5f-991036935fec.png)

I'm using the windows azure (china version)

**Comment by perrysk-msft** [comment]
Thanks for the information! 
While looking at your yaml fileI I noticed that the sa_password that you are currently using: '12345678' does not meet the SQL Server password policy requirements. Could you try using a stronger password and see if that resolves the issue. For strong password guidelines, see Authentication Mode, in SQL Server Books Online. 

For help, click: http://go.microsoft.com/fwlink?LinkID=20476&ProdName=Microsoft+SQL+Server&ProdVer=9.00.2047.00&EvtSrc=setup.rll&EvtID=28001&EvtType=sqlca%5csqlcax.cpp%40SAPasswordPolicyCheck%40SAPasswordPolicyCheck%40x6d61

**Comment by Revolution1** [comment]
I changed the password to Abc123?456

And I got this:

```
➜  nginx cat docker-compose.yml| docker-compose -p sqlserver -f - up -d
Creating sqlserver_mssql-server-2014-express-windows_1
➜  nginx docker ps
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS              PORTS                        NAMES
5015d882a872        microsoft/mssql-server-2014-express-windows:latest   "cmd /S /C 'powershel"   10 seconds ago      Up 4 seconds        47.90.1.168:1433->1433/tcp   dce-test/sqlserver_mssql-server-2014-express-windows_1
➜  nginx docker logs 5015d882a872
start-service : Failed to start service 'SQL Server (SQLEXPRESS)
(MSSQL$SQLEXPRESS)'.
At C:\start.ps1:9 char:1
+ start-service MSSQL`$SQLEXPRESS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl
   ler:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands
   .StartServiceCommand

➜  nginx cat docker-compose.yml
mssql-server-2014-express-windows:
  environment:
    sa_password: 'Abc123?456'
  image: microsoft/mssql-server-2014-express-windows:latest
  labels: {}
  ports:
  - 1433:1433
  restart: unless-stopped
```

**Comment by perrysk-msft** [comment]
Thanks! We'll investigate further and update this thread as we move forward.

**Comment by perrysk-msft** [comment]
Although compose is unlikely the cause could you please try starting the container with docker run:

Example:
docker run -p 1433:1433 --env sa_password=<YOUR SA PASSWORD> microsoft/mssql-server-2014-express-windows

**Comment by Revolution1** [comment]
[image: 内嵌图片 1]

2016-07-26 0:28 GMT+08:00 Perry Skountrianos - MSFT <
notifications@github.com>:

**Comment by Revolution1** [comment]
![image](https://cloud.githubusercontent.com/assets/3241438/17109133/4d677d2e-52c9-11e6-9c72-33aa9cadd4a9.png)
I can tell you the password and ip of remote desktop, if you mail me: crj93106@gmail.com

**Comment by perrysk-msft** [comment]
I just sent you an email.

**Comment by Revolution1** [comment]
Thank you.

**Comment by Revolution1** [comment]
Thanks for your help!

Here is the solve form @perrysk-msft 

> 1.       Stopped all running containers
> 2.       Restarted the VM
> 3.       Started the container with the following command:
> 	`docker run -p 1433:1433 --env sa_password=Password1! microsoft/mssql-server-2014-express-windows`
> 
> reason:
> 
> There is an issue (as I mentioned on the Github thread) that requires the VM to be restarted if you run/build multiple times. This issue has been addressed and will be available in the upcoming RTM release of Win Server 2016 RTM (later this year).

**Restart the after run/build multiple times**

ps: Is basically my fault that I didn't read your first reply carefully.
