### ISSUE TITLE
Error when trying to POST or PUT using nodejs-express4-rest-api

### ISSUE THREAD

**Issue by raynerhoward** [microsoft/sql-server-samples#755]
Greetings,

I am unable to POST or PUT using the two stored procedures createTodo or updateTodo. No problem with GET or GET by id using SQL Server 2017 Developer, Express or Azure SQL Database. No problem running the stored procedures from within SQL Server or Azure. It's only when trying to POST or GET via the node.js express4-tedious app that I always get the error:

message: "JSON text is not properly formatted. Unexpected character 'o' is found at position 1.",
code: 'EREQUEST',
number: 13609,
state: 4,
class: 16,
serverName: 'SERVER',
procName: 'createTodo',
lineNumber: 4

using the following curl command from within Git Bash:

curl -X "POST" "http://localhost:3000/todo"
-i
-H 'Content-Type: application/json'
-d '{"title": "test_title", "description": "test_description", "completed": false, "dueDate": "2014-12-14T00:00:00.000Z"}'

The error message using Azure SQL Database is slightly different:

JSON text is not properly formatted. Unexpected character [backslash]'o[backslash]' is found at position 1.

Any help with this would be greatly appreciated.

**Comment by raynerhoward** [comment]
Never mind, it was my curl request.  Needed to change the Content-Type from application/json to text/plain.

**Comment by MallonMafra** [comment]
> Não importa, foi o meu pedido de curl. Necessário alterar o Tipo de Conteúdo de application / json para text / plain.

Estou com mesmo problema, pode postar a correção aqui

**Comment by MallonMafra** [comment]
Agora deu certo, tava perdido aqui e ja me achei
