### ISSUE TITLE
AdventureWorksDW link broken

### ISSUE THREAD

**Issue by sdg002** [microsoft/sql-server-samples#816]
The following link is broken:
https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorkDW-oltp-install-script.zip

Source page:
https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks

Thank you

**Comment by pmasl** [comment]
See https://github.com/microsoft/sql-server-samples/tree/master/samples/databases/adventure-works#to-install-adventureworksdw
