### ISSUE TITLE
Further improvements to Java sample

### ISSUE THREAD

**Issue by marschall** [Microsoft/sql-server-samples#93]
I sent this to sqlserversamples@microsoft.com but the mail bounced to here goes.

There are several ways in which the Java Samples could be improved.
1. Idiomatic Java uses an upper case letter for the first character in
   class names. So "Connect" would be the idiomatic name of the ["connect"
   class](https://github.com/Microsoft/sql-server-samples/tree/master/samples/connect/java).
2. It would be cool if the samples where directly executable. For that
   several things would need to happen
   1. An automated build has to be set up that compiles and executes the
      code. Maven is [currently the most popular one](http://pages.zeroturnaround.com/RebelLabs-Developer-Productivity-Report-2016.html?utm_source=rebellabs_allreports&utm_medium=rebellabs&utm_campaign=rebellabs).
   2. The driver JAR can be downloaded automatically from a Maven
      repository (can be consumed by build tools other than Maven) that is
      ideally synched with [Maven Central](http://central.sonatype.org). I'm sure Sonatype would be willing to lend you a hand. This may not be in your groups
      power to do but maybe you can forward this request to the right group. Doing
      this would make lives much easier for Java developers and would put
      you ahead of proprietary competitors.
   3. A continous integration build that verifies the samples run
      successfully. That may require some code changes like reading
      connection arguments from the command line.
3. All samples  that ship with the driver package could be moved to
   GitHub and maintained there. As well as the MSDN samples.

**Comment by ajlam** [comment]
@marschall - I saw your improvements and wanted to thank you again for helping to improve our samples. 

> It would be cool if the samples where directly executable. For that several things would need to happen 
> An automated build has to be set up that compiles and executes the code. Maven is currently the most popular one.
> The driver JAR can be downloaded automatically from a Maven repository (can be consumed by build tools other than Maven) that is ideally synched with Maven Central. I'm sure Sonatype would be willing to lend you a hand. This may not be in your groups power to do but maybe you can forward this request to the right group. Doing this would make lives much easier for Java developers and would put you ahead of proprietary competitors.
> 

This is definitely something we are considering as we look to improve native Java development experiences. 

> All samples that ship with the driver package could be moved to GitHub and maintained there. As well as the MSDN samples.

Agreed. This is on the backlog of code samples to add to this repo. 

Please let me know if you have any further feedback.

**Comment by ajlam** [comment]
@marschall, closing this issue as the JDBC Driver is now on GitHub and the Java samples have been updated to Maven projects.
