### ISSUE TITLE
Can't curl the database backups anymore as it asks for a password

### ISSUE THREAD

**Issue by umbersar** [microsoft/sql-server-samples#935]
Previously I was able to download the backups for sample databases but not anymore as it asks for a password. Has the ability to download sample db backups through scripts been blocked intentionally? 

For e.g., this would work previously but now asks for a host password:
```
PS C:\Users\testuser> curl -OutFile "./database_backups/AdventureWorksDW2016.bak" "https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksDW2016.bak"
Enter host password for user 'tFile':
```

**Comment by dzsquared** [comment]
The -OutFile parameter isn't quite correct.  You want -o

```bash
PS C:\Users\testuser> curl -o "./database_backups/AdventureWorksDW2016.bak" "https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksDW2016.bak"
```

**Comment by umbersar** [comment]
Did not work. Here is the command that I ran as you suggested:

![image](https://user-images.githubusercontent.com/11863217/119564453-27a52d00-bdec-11eb-99c5-c0d98f7eeccb.png)

And here is the 1KB file that was written to disk:
![image](https://user-images.githubusercontent.com/11863217/119564579-473c5580-bdec-11eb-9a98-004b3589afc1.png)

The size of AdventureWorksDW2016.bak is actually 21,958 KB. So something is wrong here.

**Comment by dzsquared** [comment]
This seems to be most likely a network problem, does retrying at another time result in the complete file downloading?

**Comment by umbersar** [comment]
Have re-tried several times but still the same issue. A file is created on my local disk with the size 1KB.

**Comment by dzsquared** [comment]
If you click on the URL from your curl request in your terminal, does it cause the browser to download the bak file?

**Comment by umbersar** [comment]
Yes, if I click on the URL from the curl request, it does download the complete file. The downloaded file in that case has the size: _21,958_ KB

**Comment by dzsquared** [comment]
That suggests the issue is with your curl request - there is a mailing list that assists with curl community questions: https://curl.se/mail/

**Comment by umbersar** [comment]
Yes, I tested with Invoke-WebRequest and it works fine. 

`Invoke-WebRequest -OutFile c:\temp\AdventureWorksDW2016_PS.bak -URI https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksDW2016.bak `

Thanks.

**Comment by dataonthemove** [comment]
@umbersar -- Hi sorry.. kind of odd question.  I'm getting notifications for everything related to this repo ("sql-server-samples")... .. And when I try to unsubscribe using link in email footers I get "Whoops! That unsubscribe link isn't valid for your account."  (shown in attached).

I am not watching this repo but notifications persists.
Do you know why?
thx

![Untitled](https://user-images.githubusercontent.com/81224148/122995307-60133900-d3a1-11eb-9eff-f77bf60a0fc5.png)

**Comment by umbersar** [comment]
@dataonthemove sorry no idea why that is happening.

**Comment by Cardinaltruth** [comment]
Happening to me too.

**Comment by dzsquared** [comment]
@umbersar 
I actually came across this issue again and was able to replicate - instead of using curl from Windows terminal I was in an Ubuntu-based container. curl wasn’t following the GitHub release asset redirect by default.  The result was a tiny file with the correct name but the contents was a brief HTML statement about the redirect.

Adding -L to the curl command caused it to succeed.

**Comment by umbersar** [comment]
@dzsquared The strange thing is that it used to work earlier. It is only when my scripts started failing did I noticed the problem.
