### ISSUE TITLE
Double-Hop Support

### ISSUE THREAD

**Issue by peder** [Microsoft/sql-server-samples#94]
I haven't set up a test yet, but will this work with a double- or n-hop?

Some possible scenarios:
User's machine -> .NET Web Application -> Azure SQL DB
User's machine -> .NET Web Application -> .NET Application Tier -> Azure SQL DB

**Comment by peder** [comment]
Also, I wasn't sure if the user's credentials are capable of getting passed to the DB or if this is specific to service accounts

**Comment by jodebrui** [comment]
Hi, could you clarify the scenario? Which sample are you referring to, and what are you trying to accomplish?

**Comment by jodebrui** [comment]
Closing as no response on request for clarification.
