### ISSUE TITLE
SQL server installation on MAC M1 chip

### ISSUE THREAD

**Issue by afzmohammed** [microsoft/sql-server-samples#976]
I have tried many times to install SQL server 2019 using docker & I failed all the time.

My terminal shows that sql server image is exited & don't know how to fix it & Docker sql server image shows AMD arm64 error.

I was wondering if we can install SQL server on M1 chip to begin with ?

Need advice!

**Comment by dzsquared** [comment]
https://github.com/microsoft/mssql-docker/issues/668
